"""Draft a sourced Gitpa session note from a local Ableton project and garden page."""

from __future__ import annotations

import argparse
from collections import Counter
from datetime import date
import gzip
import json
from pathlib import Path
import re
import subprocess
import tempfile
from urllib.parse import quote
import xml.etree.ElementTree as ET


ROOT = Path(__file__).resolve().parents[1]
GENERATED = "<!-- Generated by scripts/draft_session_note.py. -->"
DATE_IN_NAME = re.compile(r"(?<!\d)(\d{2})[._-](\d{2})[._-](\d{2})(?!\d)")


def project_date(project: Path) -> date:
    match = DATE_IN_NAME.search(project.name)
    if not match:
        raise ValueError(f"Cannot find YY.MM.DD in project name: {project.name}")
    year, month, day = map(int, match.groups())
    return date(2000 + year, month, day)


def garden_root(explicit: Path | None) -> Path:
    if explicit:
        return explicit.resolve()
    result = subprocess.run(
        ["ghq", "list", "--full-path", "--exact", "github.com/codekiln/logseq-encode-garden"],
        check=True, capture_output=True, text=True,
    )
    return Path(result.stdout.strip()).resolve()


def find_note(garden: Path, day: date, explicit: Path | None) -> Path:
    if explicit:
        return explicit.resolve()
    marker = f"{day:%y}___{day:%m}___{day:%d}"
    matches = [
        path for path in sorted(garden.glob(f"pages/*{marker}*.md"))
        if re.search(r"\bGitP\b|\bGitpa\b", path.read_text(encoding="utf-8"), re.IGNORECASE)
    ]
    if len(matches) != 1:
        raise ValueError(f"Expected one GitP garden note for {day}; found {len(matches)}. Pass --note.")
    return matches[0]


def note_facts(note: Path) -> tuple[str, str]:
    text = note.read_text(encoding="utf-8")
    heading = re.search(r"^- # .*? with ([^\n]+)", text, re.MULTILINE | re.IGNORECASE)
    devices = heading.group(1).strip() if heading else ""
    readable = re.sub(r"\[\[([^\]]+)\]\]", lambda match: match.group(1).split("/")[-1], text)
    two_op = re.search(r"started with (?:\d+ )?two (?:operator fm|op\.?fm) on (?:an? )?initialized patch", readable, re.IGNORECASE)
    detail = "two-operator FM on an initialized patch" if two_op else ""
    return devices, detail


def explicit_description(note: Path) -> str:
    match = re.search(r"^\s*-\s*Description:\s*(.+)$", note.read_text(encoding="utf-8"), re.MULTILINE)
    return match.group(1).strip() if match else ""


def description_from_note(devices: str, detail: str) -> str:
    devices = re.sub(r"\bMicrofreak\b", "MicroFreak", devices, flags=re.IGNORECASE)
    if devices and detail:
        return f"A {devices} session beginning with {detail}."
    if devices:
        return f"A {devices} session."
    return ""


def ableton_tracks(project: Path) -> tuple[list[str], bool]:
    sets = sorted(project.glob("*.als"))
    if len(sets) != 1:
        raise ValueError(f"Expected one Ableton set in {project}; found {len(sets)}")
    with gzip.open(sets[0], "rb") as source:
        root = ET.parse(source).getroot()
    tracks: list[str] = []
    for track in root.findall(".//Tracks/*"):
        if track.tag not in {"AudioTrack", "MidiTrack"}:
            continue
        name = track.find("./Name/EffectiveName")
        if name is not None and name.get("Value"):
            label = f"{name.get('Value')} ({'MIDI' if track.tag == 'MidiTrack' else 'audio'})"
            if label not in tracks:
                tracks.append(label)
    program_changes = [
        node.get("Value") for node in root.findall(".//Tracks/MidiTrack//ProgramChange")
        if node.get("Value") not in {None, "-1"}
    ]
    return tracks, bool(program_changes)


def duration_seconds(audio: Path) -> float:
    result = subprocess.run(
        ["ffprobe", "-v", "error", "-show_entries", "format=duration", "-of", "default=noprint_wrappers=1:nokey=1", str(audio)],
        check=True, capture_output=True, text=True,
    )
    return float(result.stdout.strip())


def commentary_stem(project: Path, export_duration: float) -> tuple[Path, float] | None:
    candidates = sorted((project / "Samples" / "Recorded").glob("commentary *.aif"))
    if not candidates:
        return None
    ranked = sorted(((path, duration_seconds(path)) for path in candidates), key=lambda item: item[1], reverse=True)
    path, duration = ranked[0]
    return (path, duration) if abs(duration - export_duration) <= 10 else None


def transcript_quality(path: Path) -> tuple[bool, str]:
    data = json.loads(path.read_text(encoding="utf-8"))
    segments = [" ".join(segment.get("text", "").lower().split()) for segment in data.get("segments", [])]
    segments = [segment for segment in segments if segment]
    if len(segments) < 3:
        return False, "Too little recognized speech to support a description."
    common = Counter(segments)
    if len(segments) >= 10 and (common.most_common(1)[0][1] / len(segments) >= 0.25 or len(common) / len(segments) < 0.5):
        return False, "Repeated phrases suggest speech-recognition hallucination."
    return True, "Transcript needs a listening check before its claims are used."


def transcribe_stem(stem: Path, model: str) -> tuple[bool, str]:
    """Run speech recognition locally and discard its raw output after assessment."""
    with tempfile.TemporaryDirectory(prefix="gitpa-transcript-") as temporary:
        temporary_path = Path(temporary)
        normalized = temporary_path / "commentary.wav"
        subprocess.run(
            ["ffmpeg", "-hide_banner", "-nostdin", "-loglevel", "error", "-i", str(stem),
             "-af", "highpass=f=100,lowpass=f=5000,loudnorm=I=-18:TP=-1.5:LRA=11",
             "-ac", "1", "-ar", "16000", "-c:a", "pcm_s16le", str(normalized)],
            check=True,
        )
        subprocess.run(
            ["uv", "run", "--no-project", "--offline", "--with", "mlx-whisper==0.4.3",
             "--with", "torch==2.14.0", "--with", "mlx==0.32.2", "--with", "numba==0.67.0", "mlx_whisper",
             str(normalized), "--model", model, "--language", "en",
             "--condition-on-previous-text", "False", "--verbose", "False",
             "--output-format", "json", "--output-name", "commentary", "--output-dir", str(temporary_path)],
            check=True, capture_output=True, text=True,
        )
        return transcript_quality(temporary_path / "commentary.json")


def update_empty_description(record: Path, description: str) -> bool:
    if not description:
        return False
    if not record.is_file():
        day = date(int(record.parents[2].name), int(record.parents[1].name), int(record.parent.name))
        record.write_text(
            "published: false\n"
            f"episode_title: GitP.{day:%y.%m.%d}\n"
            f"description: {json.dumps(description)}\n"
            f"recorded_on: '{day:%Y-%m-%d}'\n"
            f"audio_file: GitP.{day:%y.%m.%d}.mp3\n"
            f"page: Ceremony/{day:%Y/%m/%d}\n",
            encoding="utf-8",
        )
        return True
    content = record.read_text(encoding="utf-8")
    updated, count = re.subn(r"(?m)^description: ''$", f"description: {json.dumps(description)}", content)
    if count:
        record.write_text(updated, encoding="utf-8")
    return bool(count)


def create_draft_page(day: date, description: str) -> Path:
    page = ROOT / "gitp-garden" / "pages" / f"Ceremony___{day:%Y}___{day:%m}___{day:%d}.md"
    if not page.exists():
        page.write_text(
            "public:: false\n"
            f"date-created:: [[{day:%Y-%m-%d %a}]]\n"
            "type:: [[Podcast/Episode]]\n\n"
            f"- # GitP.{day:%y.%m.%d}\n"
            f"\t- {description}\n",
            encoding="utf-8",
        )
    return page


def draft(project: Path, garden: Path, note: Path, transcript: Path | None, transcribe: bool, model: str) -> Path:
    day = project_date(project)
    mp3 = project / f"GitP.{day:%y.%m.%d}.mp3"
    if not mp3.is_file():
        raise FileNotFoundError(f"Prepare the MP3 before drafting: {mp3}")
    duration = duration_seconds(mp3)
    devices, detail = note_facts(note)
    description = explicit_description(note) or description_from_note(devices, detail)
    if not description:
        raise ValueError(f"No usable description facts in {note}; add a session note first")
    tracks, has_program_changes = ableton_tracks(project)
    stem = commentary_stem(project, duration)
    patch_exports = list(project.rglob("*.mfpz"))
    midi_exports = list(project.rglob("*.mid")) + list(project.rglob("*.midi"))
    note_url = "https://github.com/codekiln/logseq-encode-garden/blob/main/pages/" + quote(note.name)
    manual = garden / "pages" / "Microfreak___UG___06 Dig Osc___03 Types___08 Two Op.FM.md"
    manual_url = "https://github.com/codekiln/logseq-encode-garden/blob/main/pages/" + quote(manual.name)
    journal = garden / "journals" / f"{day:%Y_%m_%d}.md"
    journal_url = "https://github.com/codekiln/logseq-encode-garden/blob/main/journals/" + quote(journal.name)
    note_summary = "; ".join(value for value in (devices, detail) if value) or f"description supplied in the garden note: {description}"
    lines = [
        GENERATED,
        f"# GitP.{day:%y.%m.%d}",
        "",
        f"Proposed description: {description}",
        "",
        "## Evidence",
        f"- [Garden session note]({note_url}): {note_summary}.",
        f"- Prepared MP3: `{mp3.name}`, {duration / 60:.1f} minutes.",
        f"- Ableton tracks: {', '.join(tracks) if tracks else 'none named'}.",
    ]
    if journal.is_file():
        lines.append(f"- [Recording-day journal]({journal_url}) links the session note and nearby work.")
    if detail and manual.is_file():
        lines.append(f"- [MicroFreak Two Op.FM manual page]({manual_url}) explains the oscillator named in the session note.")
    if stem:
        lines.append(f"- Separate commentary recording: `{stem[0].name}`, {stem[1] / 60:.1f} minutes; a transcription candidate.")
    if transcript or transcribe:
        if transcribe and stem:
            valid, reason = transcribe_stem(stem[0], model)
        elif transcript:
            valid, reason = transcript_quality(transcript)
        else:
            valid, reason = False, "No commentary stem matches the exported episode."
        lines.append(f"- Speech recognition: {'review required' if valid else 'rejected'} — {reason}")
    lines += [
        "",
        "## Source limits",
        f"- Patch exports: {len(patch_exports)}; MIDI exports: {len(midi_exports)}. Ableton track names alone do not establish preset changes.",
        "- Ableton MIDI clips " + ("contain program-change values; inspect the active clips before naming presets." if has_program_changes else "have no program-change values that identify presets."),
        "- Check the proposed description against the recording before setting `published: true`.",
        "",
    ]
    output = ROOT / "gitp-garden" / "assets" / "Ceremony" / f"{day:%Y}" / f"{day:%m}" / f"{day:%d}" / "session-note.md"
    output.parent.mkdir(parents=True, exist_ok=True)
    if output.exists() and not output.read_text(encoding="utf-8").startswith(GENERATED):
        raise ValueError(f"Refusing to replace a hand-edited note: {output}")
    output.write_text("\n".join(lines), encoding="utf-8")
    record = output.with_name("episode.yml")
    if update_empty_description(record, description):
        print(f"Filled description in {record}")
    page = create_draft_page(day, description)
    print(f"Draft page: {page}")
    print(f"Wrote {output}")
    return output


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("project", type=Path, help="Ableton project directory")
    parser.add_argument("--garden", type=Path, help="Public Logseq garden checkout; defaults to the ghq copy")
    parser.add_argument("--note", type=Path, help="Garden session page when date lookup is ambiguous")
    speech = parser.add_mutually_exclusive_group()
    speech.add_argument("--transcript", type=Path, help="Whisper-style JSON transcript to assess")
    speech.add_argument("--transcribe", action="store_true", help="Transcribe the matching commentary stem locally with MLX Whisper")
    parser.add_argument("--model", default="mlx-community/whisper-large-v3-turbo", help="Local model directory or MLX Whisper model name")
    args = parser.parse_args()
    project = args.project.resolve()
    garden = garden_root(args.garden)
    note = find_note(garden, project_date(project), args.note)
    draft(project, garden, note, args.transcript, args.transcribe, args.model)


if __name__ == "__main__":
    main()
