REC_DIR_SUBDIRS_TO_SEARCH = ["Gdrive"]

MICROFREAK_PATCH_FILE_EXTENSION = ".mfpz"
MIDI_FILE_EXTENSION = ".mid"
EPISODE_PUBLISHING_MP3_FILE_EXTENSION = ".mix.128kbps_CBR.mp3"

FILE_SUFFIXES_TO_SYNC = [
    EPISODE_PUBLISHING_MP3_FILE_EXTENSION,
    MICROFREAK_PATCH_FILE_EXTENSION,
    MIDI_FILE_EXTENSION,
]
